# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExampleSubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.TextField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app.ExampleModel')),
            ],
        ),
    ]
